### ISSUE TITLE
Could you please release the raw text data?

### ISSUE THREAD

**Issue by yaoweilee** [artelab/Image-and-Text-fusion-for-UPMC-Food-101-using-BERT-and-CNNs#3]
The original data link in the paper "Recipe Recognition with Large Multimodal Food Dataset" has expired, and the original raw data is unavailable. Is it possible for you to release the original raw text data, too? Many thanks.

**Comment by MathscrG** [comment]
> The original data link in the paper "Recipe Recognition with Large Multimodal Food Dataset" has expired, and the original raw data is unavailable. Is it possible for you to release the original raw text data, too? Many thanks.

请问您后来找到了图片对应的文本数据集嘛？

**Comment by yaoweilee** [comment]
> release

找到了原作者，后来他们的网站又上线了一段时间，我下载好数据后，网站好像又没再维护了

**Comment by Seaz9** [comment]
> > release
> 
> 找到了原作者，后来他们的网站又上线了一段时间，我下载好数据后，网站好像又没再维护了

Hello,

You mentioned having downloaded the txt files corresponding to each image in the UPMC_Food101 dataset. Unfortunately, the website is currently inaccessible, and my attempts to contact the original authors have not received a response. Would it be possible for you to share a download link for the txt files you have locally using Google Drive or Baidu Drive? Your assistance would be highly appreciated.

Thank you very much.

**Comment by songrise** [comment]
> > > release
> > 
> > 
> > 找到了原作者，后来他们的网站又上线了一段时间，我下载好数据后，网站好像又没再维护了
> 
> Hello,
> 
> You mentioned having downloaded the txt files corresponding to each image in the UPMC_Food101 dataset. Unfortunately, the website is currently inaccessible, and my attempts to contact the original authors have not received a response. Would it be possible for you to share a download link for the txt files you have locally using Google Drive or Baidu Drive? Your assistance would be highly appreciated.
> 
> Thank you very much.

Hi, I am facing the same issue. Do you find the download link? Thanks in advance.

**Comment by yaoweilee** [comment]
Hi,
I just uploaded the zip file of all txt documents in the dataset, please find the file in the following link:

https://drive.google.com/file/d/1eywSUAJKpy8eezoFRhJbrtyOqA5mMxV1/view?usp=sharing

Hope it can help you. You can also check out our paper using the same dataset, "Efficient multimodal fusion via interactive prompting".

Kind regards.
